<?php

// ignored sidebars // ignored headers // page with custom sidebars
return [
    'configureproduct'                             => [true, false],
    'configureproductdomain'                       => [true, false],
    'configuredomains'                             => [true, false],
    'viewcart'                                     => [true, false],
    'checkout'                                     => [true, false],
    'upgradesummary'                               => [true, false],
    'complete'                                     => [true, false],
    'error'                                        => [true, false],
    'addons'                                       => [false, false],
    'creditcard'                                   => [false, false],
    'domainregister'                               => [true, false, true],
    'domaintransfer'                               => [true, false, true],
    'domain-renewals'                              => [true, false],
    'products'                                     => [true, false, true],
    'login'                                        => [true, true],
    'logintwofa'                                   => [true, true],
    'logout'                                       => [true, true],
    'clientregister'                               => [true, true],
    'error/page-not-found'                         => [true, true],
    'error/unknown-routepath'                      => [true, true],
    'pwreset'                                      => [true, true],
    'password-reset-container'                     => [true, true],
    'pwresetvalidation'                            => [true, true],
    'affiliates'                                   => [false, false, true],
    '../supportpal/viewticket'                     => [false, true],
    'contact'                                      => [true, true],
    'oauth/layout'                                 => [true, true],
    'two-factor-challenge'                         => [true, true],
    'two-factor-new-backup-code'                   => [true, true],
    'user-invite-accept'                           => [true, true],
];